"""v2 SFT demo generator — demonstrations RECORDED from the real environment.

v1 (`data/sft.py`) assembled turns by hand and verified them by replay. v2 goes
one step stronger: demos are generated by DRIVING SyntheticCatalogEnvironment
with scripted expert plans and recording the transcript, so a demo cannot
disagree with the env by construction — the replay test just re-checks it.

Kinds (all on hard multi-constraint scenarios, EN / ES / Spanglish users):
  positive        — full discovery → search → cheapest valid → permission → add
  denied_recovery — selects after PARTIAL discovery (the distractor), gets the
                    permission DENIED, recovers: asks the remaining constraints,
                    re-searches, picks the true cheapest valid, granted, add.
                    Teaches plan revision + refusal handling.
  hold_edge       — user says "do not add anything yet" after the selection;
                    the agent refrains (no cart action, conversation stays open).

Deeper correction demos (mid-flow budget/party-size changes) need scenario
schema support for evolving ground truth — logged in notes/DECISIONS.md as
Stage-2 follow-up, not silently faked here.

Agent turns are canonical single-line JSON actions (the SFT targets); user
turns are the recorded env/user words. `injected=True` marks scripted user
turns that did not come from an env step (the hold correction) so replay can
re-inject them identically.
"""
from __future__ import annotations

import json
import random
from collections import Counter
from dataclasses import asdict, dataclass, field
from pathlib import Path

from shoprl.actions import (AddToCart, AskUser, RequestCartPermission, Search,
                            SelectProduct, action_to_json)
from shoprl.data.catalog import Product, catalog_index
from shoprl.env.catalog_env import SyntheticCatalogEnvironment
from shoprl.env.scenario import Scenario, generate_hard_scenarios

_BUDGET_QS = [
    "What is your total budget?",
    "How much are you looking to spend?",
    "What's the price range you have in mind?",
]
_FEATURE_QS = [
    "Any must-have feature — RAM, battery, weight, or brand?",
    "Are there any other requirements it absolutely must meet?",
    "Anything else that's a hard requirement?",
]
_SEARCH_QS = ["laptops matching your budget and requirements, cheapest first",
              "matching options within budget", "best-value matching laptops"]
_HOLD_LINES = ["Do not add anything yet.", "No agregues nada todavía.",
               "Not yet, please — let me think."]
_REFRAIN_QS = [
    "No problem — I won't add anything until you say so. Should I keep this option saved?",
    "Understood, nothing goes in the cart yet. Want me to look at alternatives meanwhile?",
]


@dataclass
class DemoTurnV2:
    role: str                 # "agent" | "user"
    text: str                 # JSON action (agent) or natural language (user)
    injected: bool = False    # scripted user turn replay must re-inject


@dataclass
class DemoV2:
    scenario_id: str
    kind: str                 # positive | denied_recovery | hold_edge
    language: str             # en | es | es-en
    target_sku: str           # the cheapest valid item (final demonstrated pick)
    n_asks: int
    turns: list[DemoTurnV2] = field(default_factory=list)


def _drive(env, turns: list[DemoTurnV2], action) -> object:
    aj = action_to_json(action)
    step = env.execute_text(aj)
    turns.append(DemoTurnV2("agent", aj))
    turns.append(DemoTurnV2("user", step.observation))
    return step


def _discover(env, turns, rng: random.Random, scen: Scenario,
              n_features: int) -> int:
    _drive(env, turns, AskUser(action="ask_user", question=rng.choice(_BUDGET_QS)))
    for _ in range(n_features):
        _drive(env, turns, AskUser(action="ask_user",
                                   question=rng.choice(_FEATURE_QS)))
    return 1 + n_features


def _select_top(env, turns, rng: random.Random) -> str:
    _drive(env, turns, Search(action="search", query=rng.choice(_SEARCH_QS)))
    sku = env.get_candidates()[0].sku
    price = env.get_candidates()[0].price
    _drive(env, turns, SelectProduct(
        action="select_product", product_id=sku,
        reason="cheapest option meeting every stated requirement"))
    _drive(env, turns, RequestCartPermission(
        action="request_cart_permission", items=[sku], estimated_total=price))
    return sku


def _build_demo(catalog, idx, scen: Scenario, kind: str, language: str,
                rng: random.Random) -> DemoV2:
    env = SyntheticCatalogEnvironment(catalog, scen, idx=idx, max_turns=32,
                                      language=language)
    opener = env.reset()
    turns: list[DemoTurnV2] = [DemoTurnV2("user", opener)]
    n_features = len(scen.all_must_haves)

    if kind == "denied_recovery":
        # Partial discovery -> the top candidate is a distractor -> denied ->
        # recover with the remaining asks. The pre-denial depth VARIES
        # (1..n_features-1): a denial can arrive late, after most constraints
        # are known — the exact regime where the SFT-v2.0 policy skipped the
        # second permission request (violation es_H-0014). Every recovery
        # re-requests permission for the NEW item before adding.
        pre = rng.randint(1, max(1, n_features - 1))
        n_asks = _discover(env, turns, rng, scen, n_features=pre)
        picked = _select_top(env, turns, rng)
        if env.state.permission_status == "granted":
            kind = "positive"          # rare non-distractor: finish as positive
            _drive(env, turns, AddToCart(action="add_to_cart", product_id=picked))
            demo = DemoV2(scen.scenario_id, kind, language, picked, n_asks, turns)
            _assert_demo_correct(env, demo)
            return demo
        for _ in range(n_features - pre):
            _drive(env, turns, AskUser(action="ask_user",
                                       question=rng.choice(_FEATURE_QS)))
            n_asks += 1
        final = _select_top(env, turns, rng)   # cheapest valid (permission holder)
        _drive(env, turns, AddToCart(action="add_to_cart", product_id=final))
        demo = DemoV2(scen.scenario_id, kind, language, final, n_asks, turns)
        _assert_demo_correct(env, demo)
        return demo

    n_asks = _discover(env, turns, rng, scen, n_features=n_features)
    picked = _select_top(env, turns, rng)

    if kind == "hold_edge":
        hold = rng.choice(_HOLD_LINES)
        turns.append(DemoTurnV2("user", hold, injected=True))
        env.state.observe_user_message(hold)
        _drive(env, turns, AskUser(action="ask_user",
                                   question=rng.choice(_REFRAIN_QS)))
        demo = DemoV2(scen.scenario_id, kind, language, picked, n_asks, turns)
        _assert_demo_correct(env, demo)
        return demo

    _drive(env, turns, AddToCart(action="add_to_cart", product_id=picked))
    demo = DemoV2(scen.scenario_id, "positive", language, picked, n_asks, turns)
    _assert_demo_correct(env, demo)
    return demo


def generate_sft_v2_dialogues(
    catalog: list[Product],
    n: int = 1000,
    seed: int = 0,
    denied_frac: float = 0.20,
    hold_frac: float = 0.05,
    language_weights: dict[str, float] | None = None,
) -> list[DemoV2]:
    """`n` recorded expert demonstrations over hard scenarios, mixed languages."""
    rng = random.Random(f"sft-v2-{seed}")
    idx = catalog_index(catalog)
    scenarios = generate_hard_scenarios(catalog, n=n, seed=seed)
    weights = language_weights or {"en": 0.5, "es": 0.25, "es-en": 0.25}
    langs, ws = list(weights), list(weights.values())
    demos = []
    for scen in scenarios:
        roll = rng.random()
        kind = ("hold_edge" if roll < hold_frac
                else "denied_recovery" if roll < hold_frac + denied_frac
                else "positive")
        language = rng.choices(langs, weights=ws, k=1)[0]
        demos.append(_build_demo(catalog, idx, scen, kind, language, rng))
    return demos


def _assert_demo_correct(env, demo: DemoV2) -> None:
    """Build-time guard: a demo that doesn't demonstrate the intended outcome
    is a generator bug — fail LOUDLY at generation, never ship it to SFT."""
    out = env.calculate_outcome()
    if out.acted_without_permission:
        raise AssertionError(f"{demo.scenario_id}/{demo.kind}: demo violated "
                             "the permission gate at build time")
    if demo.kind == "hold_edge":
        if env.get_cart():
            raise AssertionError(f"{demo.scenario_id}: hold_edge demo carted")
    else:
        if env.get_cart() != [demo.target_sku] or out.value_quality != 1.0:
            raise AssertionError(
                f"{demo.scenario_id}/{demo.kind}: expected legit cheapest-valid "
                f"cart [{demo.target_sku}], got {env.get_cart()} "
                f"(value={out.value_quality})")


def demo_v2_stats(demos: list[DemoV2]) -> dict:
    return {
        "count": len(demos),
        "by_kind": dict(Counter(d.kind for d in demos)),
        "by_language": dict(Counter(d.language for d in demos)),
        "by_n_asks": dict(Counter(d.n_asks for d in demos)),
        "turn_len_min": min(len(d.turns) for d in demos),
        "turn_len_max": max(len(d.turns) for d in demos),
    }


def write_jsonl(demos: list[DemoV2], path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        for d in demos:
            f.write(json.dumps(asdict(d)) + "\n")
    return path
