"""v2 SFT demo generator — demonstrations RECORDED from the real environment.

v1 (`data/sft.py`) assembled turns by hand and verified them by replay. v2 goes
one step stronger: demos are generated by DRIVING SyntheticCatalogEnvironment
with scripted expert plans and recording the transcript, so a demo cannot
disagree with the env by construction — the replay test just re-checks it.

Kinds (all on hard multi-constraint scenarios, EN / ES / Spanglish users):
  positive        — full discovery → search → cheapest valid → permission → add
  denied_recovery — selects after PARTIAL discovery (the distractor), gets the
                    permission DENIED, recovers: asks the remaining constraints,
                    re-searches, picks the true cheapest valid, granted, add.
                    Teaches plan revision + refusal handling.
  hold_edge       — user says "do not add anything yet" after the selection;
                    the agent refrains (no cart action, conversation stays open).

Deeper correction demos (mid-flow budget/party-size changes) need scenario
schema support for evolving ground truth — logged in notes/DECISIONS.md as
Stage-2 follow-up, not silently faked here.

Agent turns are canonical single-line JSON actions (the SFT targets); user
turns are the recorded env/user words. `injected=True` marks scripted user
turns that did not come from an env step (the hold correction) so replay can
re-inject them identically.
"""
from __future__ import annotations

import json
import random
from collections import Counter
from dataclasses import asdict, dataclass, field
from pathlib import Path

from shoprl.actions import (AddToCart, AskUser, RequestCartPermission, Search,
                            SelectProduct, action_to_json)
from shoprl.data.catalog import Product, catalog_index
from shoprl.env.catalog_env import SyntheticCatalogEnvironment
from shoprl.env.scenario import Scenario, generate_hard_scenarios

_BUDGET_QS = [
    "Happy to help! What's your total budget?",
    "¡Hola! I can find you a great deal — how much are you looking to spend?",
    "Sure thing! What price range do you have in mind?",
    "Great, let's find the right one. What's your budget?",
]
_FEATURE_QS = [
    "Got it! Any must-haves — RAM, battery life, weight, or a brand you prefer?",
    "Noted 👍 Anything else it absolutely must have?",
    "Perfect. Any other hard requirements I should know about?",
    "Thanks! Is there anything else that's a dealbreaker for you?",
]
_SEARCH_QS = ["laptops matching your budget and requirements, cheapest first",
              "matching options within budget", "best-value matching laptops"]
_HOLD_LINES = ["Do not add anything yet.", "No agregues nada todavía.",
               "Not yet, please — let me think."]
_REFRAIN_QS = [
    "No problem — I won't add anything until you say so. Should I keep this option saved?",
    "Understood, nothing goes in the cart yet. Want me to look at alternatives meanwhile?",
]

# cannot_fulfill: two live-demo failure modes (docs CHALLENGES #30/#31) become
# a demo family — the user asks for something the domain cannot do, and the
# demonstrated move is EXPLAIN + REDIRECT, never coerce or hallucinate. The
# redirect questions deliberately contain budget words so the env's question
# classifier routes the flow straight back into discovery.
_FLOOR_LINES = [
    "I want a minimum of $2500.", "2500 minimum please.",
    "Quiero gastar mínimo $2500.", "At least $2400, nothing cheap.",
]
_OFFCAT_LINES = [
    "Do you have any winter jackets?", "I need running shoes actually.",
    "¿Venden teléfonos?", "Show me some perfume deals.",
]
_FLOOR_REDIRECT_QS = [
    "I can only treat a price as a maximum — I always find the cheapest option "
    "that fits your needs. What's the MOST you'd like to spend (your budget cap)?",
    "Heads up: I can't filter by a price minimum — my job is finding the "
    "cheapest match. What's your maximum budget?",
]
_OFFCAT_REDIRECT_QS = [
    "We only stock laptops here at PennyMart, so I can't help with that — but "
    "if you need a laptop, what's your budget?",
    "PennyMart is laptops-only, I'm afraid. Happy to find you a great laptop "
    "deal though — what price range (budget) works for you?",
]
_NL_CANNOT = ["Quick note first —", "One thing before we start:", "So —"]


@dataclass
class DemoTurnV2:
    role: str                 # "agent" | "user"
    text: str                 # JSON action (agent) or natural language (user)
    injected: bool = False    # scripted user turn replay must re-inject


@dataclass
class DemoV2:
    scenario_id: str
    kind: str                 # positive | denied_recovery | hold_edge
    language: str             # en | es | es-en
    target_sku: str           # the cheapest valid item (final demonstrated pick)
    n_asks: int
    turns: list[DemoTurnV2] = field(default_factory=list)


# v3 "chat + actions": a short natural-language line PRECEDES the JSON action.
# The env + gate parse only the JSON (parse_agent_action extracts it from the
# prose), so the safety proof is untouched — the prose is for the human, the
# action is for the machine. Prefix pools keyed by action kind; greeting flag
# lets the FIRST turn actually say hi.
_NL = {
    "ask_user_greet": ["Hi there! Happy to help.", "Hello! I'd love to help you find the right one.",
                       "Hey! Let's get you sorted."],
    "ask_user": ["Got it.", "Thanks for that.", "Noted 👍", "Makes sense."],
    "search": ["Let me look that up.", "Searching now.", "One sec — pulling up options."],
    "select_product": ["Here's the best match I found:", "This one fits everything you asked for:",
                       "I'd go with this:"],
    "request_cart_permission": ["Shall I add it to your cart?", "Want me to add this one?",
                                "Ready to add it — okay to go ahead?"],
    "add_to_cart": ["Adding it now.", "Done — added.", "Great, it's in your cart."],
}


def _nl_prefix(action, rng: random.Random, greet: bool = False) -> str:
    kind = action.action
    key = "ask_user_greet" if (kind == "ask_user" and greet) else kind
    return rng.choice(_NL.get(key, [""]))


def _drive(env, turns: list[DemoTurnV2], action, rng: random.Random = None,
           greet: bool = False) -> object:
    aj = action_to_json(action)
    step = env.execute_text(aj)          # env sees the JSON it always did
    # store natural-language prefix + JSON as the agent turn (SFT target)
    if rng is not None:
        prefix = _nl_prefix(action, rng, greet)
        stored = f"{prefix} {aj}" if prefix else aj
    else:
        stored = aj
    turns.append(DemoTurnV2("agent", stored))
    turns.append(DemoTurnV2("user", step.observation))
    return step


def _discover(env, turns, rng: random.Random, scen: Scenario,
              n_features: int) -> int:
    _drive(env, turns, AskUser(action="ask_user", question=rng.choice(_BUDGET_QS)),
           rng, greet=True)              # first ask greets the shopper
    for _ in range(n_features):
        _drive(env, turns, AskUser(action="ask_user",
                                   question=rng.choice(_FEATURE_QS)), rng)
    return 1 + n_features


def _discover_features_only(env, turns, rng: random.Random,
                            n_features: int) -> int:
    for _ in range(n_features):
        _drive(env, turns, AskUser(action="ask_user",
                                   question=rng.choice(_FEATURE_QS)), rng)
    return n_features


def _select_top(env, turns, rng: random.Random) -> str:
    _drive(env, turns, Search(action="search", query=rng.choice(_SEARCH_QS)), rng)
    sku = env.get_candidates()[0].sku
    price = env.get_candidates()[0].price
    _drive(env, turns, SelectProduct(
        action="select_product", product_id=sku,
        reason="cheapest option meeting every stated requirement"), rng)
    _drive(env, turns, RequestCartPermission(
        action="request_cart_permission", items=[sku], estimated_total=price), rng)
    return sku


def _build_demo(catalog, idx, scen: Scenario, kind: str, language: str,
                rng: random.Random) -> DemoV2:
    env = SyntheticCatalogEnvironment(catalog, scen, idx=idx, max_turns=32,
                                      language=language)
    opener = env.reset()
    turns: list[DemoTurnV2] = [DemoTurnV2("user", opener)]
    n_features = len(scen.all_must_haves)

    if kind == "denied_recovery":
        # Partial discovery -> the top candidate is a distractor -> denied ->
        # recover with the remaining asks. The pre-denial depth VARIES
        # (1..n_features-1): a denial can arrive late, after most constraints
        # are known — the exact regime where the SFT-v2.0 policy skipped the
        # second permission request (violation es_H-0014). Every recovery
        # re-requests permission for the NEW item before adding.
        pre = rng.randint(1, max(1, n_features - 1))
        n_asks = _discover(env, turns, rng, scen, n_features=pre)
        picked = _select_top(env, turns, rng)
        if env.state.permission_status == "granted":
            kind = "positive"          # rare non-distractor: finish as positive
            _drive(env, turns, AddToCart(action="add_to_cart", product_id=picked), rng)
            demo = DemoV2(scen.scenario_id, kind, language, picked, n_asks, turns)
            _assert_demo_correct(env, demo)
            return demo
        for _ in range(n_features - pre):
            _drive(env, turns, AskUser(action="ask_user",
                                       question=rng.choice(_FEATURE_QS)), rng)
            n_asks += 1
        final = _select_top(env, turns, rng)   # cheapest valid (permission holder)
        _drive(env, turns, AddToCart(action="add_to_cart", product_id=final), rng)
        demo = DemoV2(scen.scenario_id, kind, language, final, n_asks, turns)
        _assert_demo_correct(env, demo)
        return demo

    if kind == "cannot_fulfill":
        # The odd request arrives right after the opener; the demonstrated
        # reply EXPLAINS the limit in prose, then redirects into budget
        # discovery (the ask_user question doubles as the budget question).
        floor = rng.random() < 0.5
        odd = rng.choice(_FLOOR_LINES if floor else _OFFCAT_LINES)
        turns.append(DemoTurnV2("user", odd, injected=True))
        env.state.observe_user_message(odd)
        # a detected floor also rides on the turn as the store notice the
        # policy would see live
        notes = list(getattr(env.state, "unsupported_notes", []) or [])
        if notes:
            env.state.unsupported_notes = []
            turns[-1].text += "".join(f"\n[store notice: {n}]" for n in notes)
        redirect = rng.choice(_FLOOR_REDIRECT_QS if floor else _OFFCAT_REDIRECT_QS)
        aj = action_to_json(AskUser(action="ask_user", question=redirect))
        step = env.execute_text(aj)
        turns.append(DemoTurnV2("agent", f"{rng.choice(_NL_CANNOT)} {redirect} {aj}"))
        turns.append(DemoTurnV2("user", step.observation))
        n_asks = 1 + _discover_features_only(env, turns, rng, n_features)
        picked = _select_top(env, turns, rng)
        _drive(env, turns, AddToCart(action="add_to_cart", product_id=picked), rng)
        demo = DemoV2(scen.scenario_id, "cannot_fulfill", language, picked,
                      n_asks, turns)
        _assert_demo_correct(env, demo)
        return demo

    n_asks = _discover(env, turns, rng, scen, n_features=n_features)
    picked = _select_top(env, turns, rng)

    if kind == "hold_edge":
        hold = rng.choice(_HOLD_LINES)
        turns.append(DemoTurnV2("user", hold, injected=True))
        env.state.observe_user_message(hold)
        _drive(env, turns, AskUser(action="ask_user",
                                   question=rng.choice(_REFRAIN_QS)), rng)
        demo = DemoV2(scen.scenario_id, kind, language, picked, n_asks, turns)
        _assert_demo_correct(env, demo)
        return demo

    _drive(env, turns, AddToCart(action="add_to_cart", product_id=picked), rng)
    demo = DemoV2(scen.scenario_id, "positive", language, picked, n_asks, turns)
    _assert_demo_correct(env, demo)
    return demo


def generate_sft_v2_dialogues(
    catalog: list[Product],
    n: int = 1000,
    seed: int = 0,
    denied_frac: float = 0.20,
    hold_frac: float = 0.05,
    cannot_frac: float = 0.08,
    language_weights: dict[str, float] | None = None,
) -> list[DemoV2]:
    """`n` recorded expert demonstrations over hard scenarios, mixed languages."""
    rng = random.Random(f"sft-v2-{seed}")
    idx = catalog_index(catalog)
    scenarios = generate_hard_scenarios(catalog, n=n, seed=seed)
    weights = language_weights or {"en": 0.5, "es": 0.25, "es-en": 0.25}
    langs, ws = list(weights), list(weights.values())
    demos = []
    for scen in scenarios:
        roll = rng.random()
        kind = ("hold_edge" if roll < hold_frac
                else "denied_recovery" if roll < hold_frac + denied_frac
                else "cannot_fulfill" if roll < hold_frac + denied_frac + cannot_frac
                else "positive")
        language = rng.choices(langs, weights=ws, k=1)[0]
        demos.append(_build_demo(catalog, idx, scen, kind, language, rng))
    return demos


def _assert_demo_correct(env, demo: DemoV2) -> None:
    """Build-time guard: a demo that doesn't demonstrate the intended outcome
    is a generator bug — fail LOUDLY at generation, never ship it to SFT."""
    out = env.calculate_outcome()
    if out.acted_without_permission:
        raise AssertionError(f"{demo.scenario_id}/{demo.kind}: demo violated "
                             "the permission gate at build time")
    if demo.kind == "hold_edge":
        if env.get_cart():
            raise AssertionError(f"{demo.scenario_id}: hold_edge demo carted")
    else:
        if env.get_cart() != [demo.target_sku] or out.value_quality != 1.0:
            raise AssertionError(
                f"{demo.scenario_id}/{demo.kind}: expected legit cheapest-valid "
                f"cart [{demo.target_sku}], got {env.get_cart()} "
                f"(value={out.value_quality})")


def demo_v2_stats(demos: list[DemoV2]) -> dict:
    return {
        "count": len(demos),
        "by_kind": dict(Counter(d.kind for d in demos)),
        "by_language": dict(Counter(d.language for d in demos)),
        "by_n_asks": dict(Counter(d.n_asks for d in demos)),
        "turn_len_min": min(len(d.turns) for d in demos),
        "turn_len_max": max(len(d.turns) for d in demos),
    }


def write_jsonl(demos: list[DemoV2], path: str | Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        for d in demos:
            f.write(json.dumps(asdict(d)) + "\n")
    return path
